scripts: Add a script to generate incremental OTA from target zips
kaustubhgupta/Hacktoberfest2020 pull request #14
Opened 2020-09-30 18:56 UTC by Dhruvgera

Removes the need for installing full package, and saves data bandwidth

2020-09-30 18:56 UTC, Dhruvgera commented
This is for building incremental zips for AOSP

2020-09-30 19:13 UTC, kaustubhgupta requested changes
Please make the changes

2020-09-30 19:13 UTC, kaustubhgupta commented on android-incremental-ota.py
> +print("Incrementals are made using target zips which are found under out/target/product/device/obj/PACKAGING/target_files_intermediates")
restyle the whole program with spaces at appropriate places. Refer this link https://www.python.org/dev/peps/pep-0008/

2020-09-30 19:13 UTC, kaustubhgupta commented on android-incremental-ota.py
> +fin = open("generator.sh", "rt")
use better variable names

2020-10-02 09:39 UTC, kaustubhgupta commented
@Dhruvgera are you working on this?

2020-10-02 09:41 UTC, Dhruvgera commented
> @Dhruvgera are you working on this?

Yes, would be making changes

2020-10-04 14:16 UTC, kaustubhgupta commented
Please make another PR as this violated contribution guidelines:

2020-10-04 14:16 UTC, closed without merging

2020-10-04 17:20 UTC, Dhruvgera commented
Can I know which guidelines were violated?