Create Palindrome_Substrings.py
kaustubhgupta/Hacktoberfest2020 pull request #146
Opened 2020-10-03 09:28 UTC by deVedant

# Palindrome Substrings

Fixes #73 

## Written a program in python to find all palindrome substrings in a string input by user. 

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation
-   [x] My changes generates no new warnings

2020-10-03 12:27 UTC, kaustubhgupta requested changes

2020-10-03 12:27 UTC, kaustubhgupta commented on Python/Palindrome_Substrings.py
> +s = input("Enter a string : ")
- use driver code for better code readability. Refer this page for the same: 
https://docs.python.org/3.7/library/__main__.html

- Also, make the entry of this program in the Python directory readme.

2020-10-03 17:57 UTC, kaustubhgupta commented
@deVedant Code is fine now, can you update the Python directory readme too so that it can be merged?

2020-10-03 18:03 UTC, deVedant commented
> @deVedant Code is fine now, can you update the Python directory readme too so that it can be merged?

Actually this is my another account and I'm working on my mobile. I am some 48 commits behind master 😅Issue is pulling(fetching) changes as this feature ain't on mobile.
Could you please do it for me?

2020-10-04 13:51 UTC, kaustubhgupta commented
@deVedant Okay, we can make an exception for you. Code reviewed and accepted!

2020-10-04 13:51 UTC, merged