add scientific calcultor
kaustubhgupta/Hacktoberfest2020 pull request #169
Opened 2020-10-03 18:23 UTC by ishanbagchi

# add a Scientific Calculator

Add a command-line scientific calculator that does a little more than classical addition, subtraction, multiplication, and division. It calculates the sin, cos, tan, and much more like this.

Fixes: #125

## Add a scientific calculator in Python language and an instruction.md file

Please delete options that are not relevant.

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [x] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [x] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-04 05:48 UTC, kaustubhgupta requested changes
Please correct the following things

2020-10-04 05:48 UTC, kaustubhgupta commented on Python/Calculator/INSTRUCTIONS.md
> +Operators|Functions
The readme needs proper alignment right now it's all messed up:
![image](https://user-images.githubusercontent.com/43691873/95007881-50e13500-0632-11eb-8142-a9e654e00619.png)

2020-10-04 05:48 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +'''
Remove this docstring as you have created a separated file for this

2020-10-04 05:48 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +print ("Please read instructions in the code\nor reach https://github.com/kaustubhgupta/Hacktoberfest2020_ for help \n*************************")
Remove this print statement

2020-10-04 05:48 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +firstNumber = float(input())
While taking input, print something

2020-10-04 05:48 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +if op == "+":
Implement a class-based code, move all this code to a class, and create separate functions for each operation. If the operator requires only one operand then don't take the second number input and directly output the result.

2020-10-04 05:49 UTC, kaustubhgupta requested changes

2020-10-04 05:49 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +    print ("incorrect operator")
Make the entry of this program in Python directory readme

2020-10-04 05:59 UTC, ishanbagchi commented
@kaustubhgupta sorry for the inconvenience. I'll correct it right away.

2020-10-04 12:48 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +    theNumber = firstNumber = secondNumber
What is this?

2020-10-04 12:49 UTC, kaustubhgupta requested changes

2020-10-04 12:49 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +if op == "+":
What about the class code?

2020-10-04 13:27 UTC, ishanbagchi commented
@kaustubhgupta for this simple calculator program, if else is comparatively easy. So I thought of do it in this manner.

2020-10-04 16:13 UTC, kaustubhgupta commented
@ishanbagchi okay don't implement class code but fix the error I pointed.

2020-10-04 16:19 UTC, ishanbagchi commented
> @ishanbagchi okay don't implement class code but fix the error I pointed. 

Which error? I solved the error in INSTRUCTIONS.md, added the link in the language README.me, removed the print statement with the link. Anything else was there? 👀

2020-10-05 05:08 UTC, kaustubhgupta commented on Python/Calculator/calculator.py
> +    theNumber = firstNumber = secondNumber
The line 39 doesn't seem right

2020-10-05 15:39 UTC, ishanbagchi commented on Python/Calculator/calculator.py
> +    theNumber = firstNumber = secondNumber
This is correct.

2020-10-05 16:41 UTC, kaustubhgupta approved these changes

2020-10-05 16:42 UTC, merged