added a password_manager app. in python section.
kaustubhgupta/Hacktoberfest2020 pull request #189
Opened 2020-10-05 13:06 UTC by shaalwan

# Title/Heading < Edit this part>

added a password management app in python. python needs to be installed in you system to run this application < Edit this part>

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] New feature (non-breaking change which adds functionality)

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-05 15:14 UTC, kaustubhgupta commented
@shaalwan kindly fill the PR template properly with all entries

2020-10-05 15:20 UTC, kaustubhgupta requested changes

2020-10-05 15:20 UTC, kaustubhgupta commented on Python/password-manager.pyw
> +# imports
Remove extra spaces from the program

2020-10-05 15:20 UTC, kaustubhgupta commented on Python/password-manager.pyw
> +e = IntVar()
User better variable name here

2020-10-05 15:20 UTC, kaustubhgupta commented on Python/password-manager.pyw
> +root.mainloop()  # loop that allows GUI to run
- The code is fine, do the changes suggested in the beginning. Also, attach a GIF showing the working of the program, its functions as right now it's difficult to judge whether it is working or not. Put both the files (GIF and code file in a folder and put that folder under the Python directory. 
- Update the language folder readme too :-)

2020-10-05 20:44 UTC, shaalwan commented
i did changes and pushed them to shaalwan branch. please look into it. thank you!

2020-10-06 04:07 UTC, kaustubhgupta approved these changes

2020-10-06 04:10 UTC, merged

2020-10-06 04:10 UTC, kaustubhgupta commented
@shaalwan Thanks for contribution!