Contribution
kaustubhgupta/Hacktoberfest2020 pull request #199
Opened 2020-10-05 17:11 UTC by adilsp5075

# Title/Heading < Edit this part>

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < Edit this part>

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-05 17:12 UTC, adilsp5075 commented
menu driven calculator with extra two functions

2020-10-06 04:19 UTC, kaustubhgupta requested changes

2020-10-06 04:19 UTC, kaustubhgupta commented on README.md
>  ## Happy?? Do Star ⭐ this Repo. 🤩
I have not asked to edit this

2020-10-06 04:19 UTC, kaustubhgupta commented on my calc/my calculator.c
> +#include <stdio.h>
Put the files (image and code) in the appropriate directory (C folder) and edit that folder readme with your entry (you will understand once you look at it)

2020-10-06 04:22 UTC, adilsp5075 commented
Sorry for the inconvenience I will check it out

On Tue, Oct 6, 2020, 9:49 AM Kaustubh <notifications@github.com> wrote:

> *@kaustubhgupta* requested changes on this pull request.
> ------------------------------
>
> In README.md
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/199#discussion_r499996310>
> :
>
> > @@ -32,3 +32,5 @@ Voila!
>
>  ## Happy?? Do Star ⭐ this Repo. 🤩
>
>
> I have not asked to edit this
> ------------------------------
>
> In my calc/my calculator.c
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/199#discussion_r499996605>
> :
>
> > @@ -0,0 +1,68 @@
>
> +#include <stdio.h>
>
>
> Put the files (image and code) in the appropriate directory (C folder) and
> edit that folder readme with your entry (you will understand once you look
> at it)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/199#pullrequestreview-502571544>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARHMK6QOZZROZ6T6K5KSKJTSJKLFDANCNFSM4SE6QNXA>
> .
>

2020-10-06 05:28 UTC, kaustubhgupta commented
You made another PR, this will be considered invalid

2020-10-06 05:28 UTC, closed without merging