Create folderSeperator.py
kaustubhgupta/Hacktoberfest2020 pull request #220
Opened 2020-10-06 14:57 UTC by MayankDev-11

This is a snake game made by me.

# Title/Heading < File seperator>

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < This is a pygame >

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-07 04:58 UTC, kaustubhgupta requested changes

2020-10-07 04:58 UTC, kaustubhgupta commented on Python/folderSeperator.py
> +import os
Please update the readme of the language folder

2020-10-07 04:58 UTC, kaustubhgupta commented on Python/folderSeperator.py
> +
Remove this extra line

2020-10-07 11:32 UTC, ByGreez commented on Python/folderSeperator.py
> +files.remove("folder_Cleaner.py")
```suggestion
files.remove("folderSeperator.py")
```

2020-10-07 14:11 UTC, MayankDev-11 commented
Yes bro i will add this feature too.Working on it

On Wed 7 Oct, 2020, 5:02 PM Val Gromov, <notifications@github.com> wrote:

> *@ByGreez* commented on this pull request.
> ------------------------------
>
> In Python/folderSeperator.py
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/220#discussion_r500939044>
> :
>
> > +import os
>
> +
>
> +
>
> +def createIfNotExists(folder):
>
> +    if not os.path.exists(folder):
>
> +        os.makedirs(folder)
>
> +
>
> +
>
> +def move(foldername,files):
>
> +    for file in files:
>
> +        os.replace(file, f"{foldername}/{files}")
>
> +        print("Ok")
>
> +
>
> +
>
> +files = os.listdir()
>
> +files.remove("folder_Cleaner.py")
>
>
> ⬇️ Suggested change
>
> -files.remove("folder_Cleaner.py")
>
> +files.remove("folderSeperator.py")
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/220#pullrequestreview-503782503>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARIUPZYPH2KT3IFZ3M4IZ4TSJRGUPANCNFSM4SGEQHVQ>
> .
>

2020-10-09 04:04 UTC, kaustubhgupta commented
@MayankDev-11 If you fail to make changes within 7 days of opening the PR it will be marked as stale and on the 10th day it will be closed automatically, just an update

2020-10-10 05:58 UTC, kaustubhgupta requested changes

2020-10-10 05:58 UTC, kaustubhgupta commented on Python/folderSeperator.py
> +import os
Update readme folder of the Python folder with your entry

2020-10-15 06:25 UTC, kaustubhgupta commented
Due to inactivity, this PR has been closed

2020-10-15 06:25 UTC, closed without merging