HackToberFest2020
kaustubhgupta/Hacktoberfest2020 pull request #224
Opened 2020-10-07 05:40 UTC by sonalimahajan12

# Title/Heading < Edit this part>

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < Edit this part>

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-07 07:18 UTC, kaustubhgupta commented
@sonalimahajan12 create the issue of the same and fill this PR template

2020-10-07 08:14 UTC, YashSaxena9 commented
Please follow the contribution guide :)

2020-10-08 08:33 UTC, kaustubhgupta requested changes

2020-10-08 08:33 UTC, kaustubhgupta commented on C++/Sliding Window Maximum (Maximum of all subarrays of size k).cpp
> +#include<bits/stdc++.h>
Have a look at contribution guidelines

2020-10-11 05:18 UTC, closed without merging

2020-10-17 13:04 UTC, sonalimahajan12 commented
Hi kaustubh ,

can you open this issue again? I will do it again as per your requirements.

or should I again make pull request.

On Sun, Oct 11, 2020 at 10:48 AM Kaustubh <notifications@github.com> wrote:

> Closed #224 <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/224>
> .
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/224#event-3863353890>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AIOARM46F5NWRBLSCILQR3TSKE5ZPANCNFSM4SG5MNXQ>
> .
>