Adding Code of Game
kaustubhgupta/Hacktoberfest2020 pull request #264
Opened 2020-10-08 06:44 UTC by bhavesh1129

#Guessing Game < Edit this part>

I had added a small code in the C language of the Guessing Game.
It is basically a guessing game that allows users to enter any random number within a specific range.
It also provides some chances to users so that if in case their first guess is wrong they may try one more time.
< Edit this part>

Fixes #257 

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented on my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generate no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-08 08:56 UTC, kaustubhgupta requested changes

2020-10-08 08:56 UTC, kaustubhgupta commented on C/Guessing Game/main.c
> +#include <stdio.h>
- Remove the exe file
- add comments to this program
- add GIF demonstrating the game
- place that GIF in the same folder Guessing Game  you created
- edit readme of C folder with your entry

2020-10-08 17:24 UTC, bhavesh1129 commented
Hey!
I had made the following changes mentioned by you. 
Please check my PR and if you find it good then merge it to your repo.
Thank you!

2020-10-09 04:09 UTC, kaustubhgupta approved these changes

2020-10-09 04:09 UTC, merged