added 3 java programs
kaustubhgupta/Hacktoberfest2020 pull request #269
Opened 2020-10-08 08:37 UTC by AnOnYmOus001100

# Title/Heading < Edit this part>

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. < Edit this part>

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works
-   [ ] New and existing unit tests pass locally with my changes
-   [ ] Any dependent changes have been merged and published in downstream modules

2020-10-08 09:11 UTC, kaustubhgupta commented
@AnOnYmOus001100 Can you specify which issue has been assigned to you?

2020-10-08 09:23 UTC, AnOnYmOus001100 commented
Here is the issue
want to add basic java programs #270

2020-10-08 12:19 UTC, kaustubhgupta requested changes

2020-10-08 12:19 UTC, kaustubhgupta commented on Java/factorial.java
> +/**
Remove these doc strings from all files

2020-10-08 12:19 UTC, kaustubhgupta commented on Java/factorial.java
> +	Author: AnOnYmOus001100
Remove extra spaces from programs

2020-10-08 12:19 UTC, kaustubhgupta commented on Java/factorial.java
> +	Date: 04/10/2020
Update the readme of Java folder

2020-10-08 14:34 UTC, AnOnYmOus001100 commented
ok, done removing the docstrings. updated the codes

2020-10-09 04:35 UTC, kaustubhgupta approved these changes

2020-10-09 04:35 UTC, merged