Quick sort added
kaustubhgupta/Hacktoberfest2020 pull request #313
Opened 2020-10-09 07:07 UTC by DefCon-018

# Description

I have added quick sort algorithm to c++ folder and also updated README.md file

Fixes #283 

## Type of change

**Please delete options that are not relevant**

# Checklist:

-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

2020-10-09 09:14 UTC, DefCon-018 commented
@kaustubhgupta please review this PR.

2020-10-09 09:17 UTC, kaustubhgupta requested changes

2020-10-09 09:17 UTC, kaustubhgupta commented on C++/Quick_Sort.cpp
> +/*
Remove this doc string

2020-10-09 16:18 UTC, YashSaxena9 requested changes
Your logic behind code looks fine, please remove the starting docstring :)

2020-10-10 02:21 UTC, DefCon-018 commented
first docstring removed

2020-10-10 06:09 UTC, kaustubhgupta requested changes

2020-10-10 06:09 UTC, kaustubhgupta commented on C++/Quick_Sort.cpp
> +Input format :
The whole doc string

2020-10-10 06:23 UTC, DefCon-018 commented
Removed whole docstring

2020-10-10 09:02 UTC, kaustubhgupta approved these changes

2020-10-10 09:03 UTC, merged