Add Subsets of a String to Java
kaustubhgupta/Hacktoberfest2020 pull request #319
Opened 2020-10-09 09:39 UTC by varad64

# Description
Added Recursive implementation for the problem of printing all the subsets of a string in Java.

Fixes #316 

**Please delete options that are not relevant**

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings

2020-10-09 16:20 UTC, YashSaxena9 approved these changes
Code looks good, but use of stringbuilder is advised for string operations in java. :)

2020-10-09 16:44 UTC, varad64 commented
> Code looks good, but use of stringbuilder is advised for string operations in java. :)

Alright @YashSaxena9  will switch to StringBuilder

2020-10-10 06:24 UTC, kaustubhgupta requested changes

2020-10-10 06:24 UTC, kaustubhgupta commented on Java/SubsetsOfAString.java
> +import java.io.BufferedReader;
Update Java folder readme with your entry

2020-10-10 06:49 UTC, varad64 commented on Java/SubsetsOfAString.java
> +import java.io.BufferedReader;
Done @kaustubhgupta

2020-10-10 09:04 UTC, kaustubhgupta approved these changes

2020-10-10 09:04 UTC, merged