Child
kaustubhgupta/Hacktoberfest2020 pull request #326
Opened 2020-10-09 12:54 UTC by 13snehitha

# 287 kadane's algorithm full code written in python

Please include a summary of the changes you have made in regard with this issue. 

Fixes #(issue number)

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-10 06:14 UTC, kaustubhgupta requested changes
- Make changes suggested by code factor
- Update Python folder readme with your entry
- Make these changes:

2020-10-10 06:14 UTC, kaustubhgupta commented on Python/kadanes_algo.py
> +ip=list(map(int,input("Enter array elements").split()))
- Poor code formating
- Refactor the whole program with spaces, comments

2020-10-10 06:14 UTC, kaustubhgupta commented on Python/kadanes_algo.py
> +
Remove these extra lines

2020-10-11 10:33 UTC, 13snehitha commented
@kaustubhgupta 
Requested changes are updated

2020-10-11 10:53 UTC, 13snehitha commented
@kaustubhgupta 
Updated the readme file and program .

2020-10-12 04:38 UTC, kaustubhgupta approved these changes

2020-10-12 04:38 UTC, merged