adding kadane's algorithm in c
kaustubhgupta/Hacktoberfest2020 pull request #333
Opened 2020-10-09 17:38 UTC by rgarg-2711

# Description adding kadane's algorithm in c

Please include a summary of the changes you have made in regard with this issue. 

Fixes #(issue number) #287 

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-09 17:40 UTC, rgarg-2711 commented
in reference to issue #287

2020-10-10 06:16 UTC, kaustubhgupta requested changes

2020-10-10 06:16 UTC, kaustubhgupta commented on C/kadane.c
> +/*run the test case
Remove this doc string

2020-10-10 07:46 UTC, rgarg-2711 commented
in reference to issue #287 update the kadane's algo in c

2020-10-10 09:20 UTC, kaustubhgupta commented
@YashSaxena9 Again strong sus of plagiarism :
See this: (Maybe I am wrong )
https://gist.github.com/sujaykundu777/a1a72c88291f9ee72aaba02b80159bf7

2020-10-10 11:06 UTC, rgarg-2711 commented
I did it on my personal IDE.It's the basic code find everywhere same.

2020-10-12 08:13 UTC, kaustubhgupta approved these changes

2020-10-12 08:14 UTC, merged