Insertion linked list java
kaustubhgupta/Hacktoberfest2020 pull request #355
Opened 2020-10-10 09:41 UTC by jindalsachin

# Description

Please include a summary of the changes you have made in regard with this issue. 

Fixes #(issue number)

## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-10 15:35 UTC, kaustubhgupta commented
@jindalsachin Fill PR template properly with appropriate issue number

2020-10-10 17:09 UTC, jindalsachin commented
@kaustubhgupta I have filled the PR template Please check

2020-10-11 13:12 UTC, kaustubhgupta requested changes

2020-10-11 13:12 UTC, kaustubhgupta commented on InsertionLinkedList.java
> +I have implemented all 3 insertion in simple program with the hellp of 3 different classes respecively.
- Delete this line
- Update java folder readme

2020-10-12 08:05 UTC, kaustubhgupta commented
https://www.geeksforgeeks.org/linked-list-set-2-inserting-a-node/
Not acceptable

2020-10-12 08:05 UTC, closed without merging