Added Extra Long Factorial
kaustubhgupta/Hacktoberfest2020 pull request #357
Opened 2020-10-10 10:37 UTC by AtalKhandelwal

# Description

Program for Extra Long Factorials like 60!, 100!etc.

Fixes #353

## Type of change

-   [x] New feature (non-breaking change which adds functionality)
-   [x] This change requires a documentation update

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

2020-10-10 10:40 UTC, AtalKhandelwal commented
@kaustubhgupta Please review this PR.

2020-10-10 15:04 UTC, kaustubhgupta requested changes

2020-10-10 15:04 UTC, kaustubhgupta commented on Java/README.md
> +|           Extra Long Factorials        |        [link](./ExtraLongFactorial.java)                  |
Why you deleted the previous entries here?

2020-10-11 10:09 UTC, AtalKhandelwal commented
@kaustubhgupta  Sorry! It might get deleted by mistake. I have updated readme with these entries.

2020-10-11 13:09 UTC, kaustubhgupta approved these changes

2020-10-12 12:52 UTC, YashSaxena9 approved these changes
Code looks fine, thank you for your hardwork :)

2020-10-12 12:53 UTC, YashSaxena9 commented
@kaustubhgupta seems like some merge conflicts have occurred !

2020-10-12 14:20 UTC, merged