Create reverse_doubly_linked_list.java
kaustubhgupta/Hacktoberfest2020 pull request #376
Opened 2020-10-11 07:41 UTC by manishita24

# Description

I added a program to reverse Doubly link list in java language

Fixes ##349

## Type of change

-   [x] New feature (non-breaking change which adds functionality)

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

2020-10-11 13:06 UTC, kaustubhgupta requested changes

2020-10-11 13:06 UTC, kaustubhgupta commented on Main.java
> +public class Main {
update java folder readme

2020-10-12 12:39 UTC, YashSaxena9 requested changes
Points to be changed
- rename file to reverseDoublyLinkedList.java
- update readme

Advice(just a tip for style improvement)
- you can override toString() function in java instead of explicitly writting display function.

2020-10-12 15:19 UTC, manishita24 commented
sheesh, I am bad at this. 😭😭😭 I hope it is fine now

2020-10-12 15:25 UTC, kaustubhgupta commented
@manishita24 Ahh code is perfectly fine now but you need to update the Java readme file too :-) 
Just update that one with your entry and this PR will be merged

2020-10-12 17:02 UTC, manishita24 commented
Done. Thank you for your patience and help.

2020-10-15 06:36 UTC, kaustubhgupta approved these changes

2020-10-15 06:38 UTC, merged

2020-10-15 06:39 UTC, kaustubhgupta commented
@manishita24 Perfect thanks for contributing here! 😋