Create RevDoublyLinkedList.c
kaustubhgupta/Hacktoberfest2020 pull request #41
Opened 2020-10-01 06:03 UTC by Code-Recursion

2020-10-01 16:16 UTC, kaustubhgupta commented
@Code-Recursion Provide a proper description, reformat the code with additional comments. Your PR can be merged then

2020-10-01 17:17 UTC, YashSaxena9 commented
Proper documentation required

2020-10-01 17:18 UTC, YashSaxena9 requested changes

2020-10-01 17:18 UTC, YashSaxena9 commented on C++/RevDoublyLinkedList.c
> +#include <stdio.h>
Proper documentation / comments missing for funcitonality description

2020-10-02 07:31 UTC, YashSaxena9 approved these changes
PR accepted for merge :)

2020-10-02 07:32 UTC, merged