[#391] script to convert pdf tables to mongo collections
kaustubhgupta/Hacktoberfest2020 pull request #416
Opened 2020-10-15 04:54 UTC by meghnabhave

# Description

Script to convert tables in pdf to MongoDB collections.

Fixes #391 

## Type of change

**Please delete options that are not relevant**

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-15 06:57 UTC, kaustubhgupta requested changes

2020-10-15 06:57 UTC, kaustubhgupta commented on Python/pdf_to_mongodb/pdfmongo.py
> +import pandas as pd
You have not mentioned this (pandas)  in the dependencies in the readme file. Kindly do that.

2020-10-15 06:57 UTC, kaustubhgupta commented on Python/pdf_to_mongodb/pdfmongo.py
> +    collection_id += 1
I think you didn't read the issue correctly, you need to create another file to query the database created to display the results/items extracted from the PDF.

Also, remove these semicolons

2020-10-15 06:57 UTC, kaustubhgupta commented on Python/pdf_to_mongodb/pdfmongo.py
> +pdf_path = "data.pdf";
take input of the PDF file instead of hardcoding it. You can use command-line arguments parser or directly using input() that's your choice.

2020-10-19 09:43 UTC, kaustubhgupta commented
@meghnabhave Are you working on making the changes?

2020-10-20 08:35 UTC, meghnabhave commented
yes kaustubh, will update the PR soon

Apologies for the delay

On Mon, Oct 19, 2020 at 3:13 PM Kaustubh <notifications@github.com> wrote:

> @meghnabhave <https://github.com/meghnabhave> Are you working on making
> the changes?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/kaustubhgupta/Hacktoberfest2020_/pull/416#issuecomment-711943065>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFCLSOCOLGWR2PDZBDQGT6LSLQC5TANCNFSM4SRPAMLA>
> .
>

2020-10-23 04:13 UTC, kaustubhgupta commented
Failing to do changes will reject this PR, just a heads up

2020-10-23 11:54 UTC, closed without merging