Add permutation_of_string.c
kaustubhgupta/Hacktoberfest2020 pull request #426
Opened 2020-10-15 13:15 UTC by alvinuday

Permutations of a given string in C

# Description

Please include a summary of the changes you have made in regard with this issue. 
C code for permutations of a given string

Fixes #(issue number)
#401 
## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [x] I have read the contribution guidelines before making this PR.
-   [x] My code follows the style guidelines of this project
-   [x] I have performed a self-review of my own code
-   [x] I have commented in my code, particularly in hard-to-understand areas
-   [x] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [x] My changes generates no new warnings
-   [x] I have added tests that prove my fix is effective or that my feature works

2020-10-16 14:10 UTC, alvinuday commented
is something wrong with the code? @kaustubhgupta

2020-10-16 14:13 UTC, alvinuday commented
![Screen Shot 2020-10-16 at 7 41 17 PM](https://user-images.githubusercontent.com/72704414/96269279-ce6c5400-0fe7-11eb-93c9-882b6bc4549e.png)

I think the permutations are fine.
if there is any problem please revert

2020-10-17 08:14 UTC, alvinuday commented
what improvement is needed? @kaustubhgupta @YashSaxena9

2020-10-17 12:05 UTC, kaustubhgupta commented
@alvinuday @YashSaxena9 Will suggest changes. Wait for him to review your PR

2020-10-18 05:17 UTC, kaustubhgupta requested changes

2020-10-18 05:17 UTC, kaustubhgupta commented on C/permutation_of_string.c
> +#include <stdio.h>
update C folder readme file

2020-10-18 05:30 UTC, kaustubhgupta commented
The PR is not linked to any issue, kindly fix that

2020-10-18 06:28 UTC, closed without merging