Add files via upload
kaustubhgupta/Hacktoberfest2020 pull request #443
Opened 2020-10-16 20:32 UTC by AK271

# Description

Java code for Trie Node implementation

Fixes #421 

## Type of change
Added Java file

**Please delete options that are not relevant**

-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-17 12:03 UTC, kaustubhgupta requested changes

2020-10-17 12:03 UTC, kaustubhgupta commented on Java/Trie_Implementation.java
> +import java.util.Scanner;
Update java folder readme

2020-10-17 12:05 UTC, kaustubhgupta commented
@AK271 Edit this PR title

2020-10-17 12:43 UTC, AK271 commented
I have updated the java folder README.md and added the program and link

2020-10-18 07:56 UTC, YashSaxena9 approved these changes
Implementation seems correct for Trie, thank you for your hard work :)

2020-10-18 07:57 UTC, YashSaxena9 commented
PR accepted for merge :)

2020-10-18 07:57 UTC, merged

2020-10-18 08:01 UTC, AK271 commented
Thank you!