Create Probability of getting at least K heads in N tosses of CoinsPr…
kaustubhgupta/Hacktoberfest2020 pull request #454
Opened 2020-10-17 12:16 UTC by aastha01chauhan

…obability of getting at least K heads in N tosses of Coins

# Description
I have endeavoured to provide the most optimised solution by myself. This problem revolves around the concept of probability and binomial theorem.

Fixes #331 Probability of getting at least K heads in N tosses of Coins

## Type of change

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] I have read the contribution guidelines before making this PR.
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented in my code, particularly in hard-to-understand areas
-   [ ] I have made corresponding changes to the documentation (Language folder or any other readme instructed to)
-   [ ] My changes generates no new warnings
-   [ ] I have added tests that prove my fix is effective or that my feature works

2020-10-18 05:15 UTC, kaustubhgupta requested changes
- The file name is incorrect without any extension. 
- Java folder readme has not been updated
- Pull request template not filled correctly

2020-10-18 08:00 UTC, YashSaxena9 requested changes

2020-10-18 08:00 UTC, YashSaxena9 commented on Java/Probability of getting at least K heads in N tosses of CoinsProbability of getting at least K heads in N tosses of Coins
> +// JAVA Code for Probability of getting
file extension missing, and code format is not good

2020-10-20 09:13 UTC, aastha01chauhan commented
I'll just correct it.

2020-10-23 04:13 UTC, kaustubhgupta commented
Failing to do changes will reject this PR, just a heads up

2020-10-23 11:52 UTC, closed without merging