Create max_heap_Sort.py
kaustubhgupta/Hacktoberfest2020 pull request #620
Opened 2021-10-01 03:50 UTC by bvsslgayathri-8679

# Description

Please include a summary of the changes you have made in regard with this issue. 

## Fixes: #(issue number) 
#620
## Type of change

**Please delete options that are not relevant**

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [X] New feature (non-breaking change which adds functionality)
-   [ ] This change requires a documentation update

# Checklist:

-   [X] I have read the contribution guidelines before making this PR.
-   [X] I have performed a self-review of my own code

2021-10-02 03:52 UTC, kaustubhgupta requested changes

2021-10-02 03:52 UTC, kaustubhgupta commented on Python/max_heap_Sort.py
> +array=list(map(int,input('enter tree elements ').split()))
```suggestion
array=list(map(int,input('Enter Tree Elements ').split()))
```

2021-10-02 03:52 UTC, kaustubhgupta commented on Python/max_heap_Sort.py
> +print("ascending sort of given array is ",array)
```suggestion
print("Ascending Sort of Given Array is ",array)
```

2021-10-02 03:53 UTC, kaustubhgupta commented
- Create an issue for this PR and link it.

2021-10-02 08:05 UTC, bvsslgayathri-8679 commented
Yeah I have updated the changes

2021-10-04 04:34 UTC, kaustubhgupta commented
No issue has been created for this PR. Create an issue and like it this PR

2021-10-05 05:25 UTC, closed without merging