Create Bresenham-Circle.c
kaustubhgupta/Hacktoberfest2020 pull request #89
Opened 2020-10-01 17:40 UTC by Utkarsh2604

# Title/Heading

Bresenham Circle Drawing Algorithm using C.

# Checklist:
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [x ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x ] My changes generates no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2020-10-01 18:05 UTC, Utkarsh2604 commented
please merge my pr

2020-10-02 07:59 UTC, kaustubhgupta requested changes

2020-10-02 07:59 UTC, kaustubhgupta commented on C/Bresenham-Circle.c
> +#include <stdio.h>
Please add some documentation in the form of comments to explain what the Bresenham Algorithm is all about, why it is faster than the midpoint algorithm

2020-10-02 07:59 UTC, kaustubhgupta commented on C/Bresenham-Circle.c
> +      if(d<=0)
use better variable names

2020-10-02 07:59 UTC, kaustubhgupta commented on C/Bresenham-Circle.c
> +     return 0;
added a screenshot of the program and put both files (code and output) in one folder under the C directory

2020-10-04 14:19 UTC, kaustubhgupta commented
@Utkarsh2604 are you working on this ?

2020-10-06 14:42 UTC, merged